// export const restaurants = [
//   {
//     info: {
//       id: "17036",
//       name: "Leon's - Burgers & Wings (Leon Grill)",
//       cloudinaryImageId: "b2edbc28b7b8219d6e0a9c049ce06658",
//       locality: "HSR Layout",
//       areaName: "HSR Layout",
//       costForTwo: "₹300 for two",
//       cuisines: ["American", "Snacks", "Turkish", "Portuguese", "Continental"],
//       avgRating: 4.5,
//       parentId: "371281",
//       avgRatingString: "4.5",
//       totalRatingsString: "10K+",
//       sla: {
//         deliveryTime: 34,
//         lastMileTravel: 4.6,
//         serviceability: "SERVICEABLE",
//         slaString: "34 mins",
//         lastMileTravelString: "4.6 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-07 04:00:00",
//         opened: true,
//       },
//       badges: {},
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {},
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/leons-burgers-and-wings-leon-grill-hsr-layout-bangalore-17036",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "289257",
//       name: "BOX8 - Desi Meals",
//       cloudinaryImageId: "69a061b7e0f951cef2b4947946f94ec6",
//       locality: "Harlur Main Road",
//       areaName: "HSR Layout",
//       costForTwo: "₹250 for two",
//       cuisines: ["North Indian", "Biryani", "Thalis", "Home Food"],
//       avgRating: 4.4,
//       parentId: "10655",
//       avgRatingString: "4.4",
//       totalRatingsString: "1K+",
//       sla: {
//         deliveryTime: 19,
//         lastMileTravel: 1.5,
//         serviceability: "SERVICEABLE",
//         slaString: "14-24 mins",
//         lastMileTravelString: "1.5 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-07 02:00:00",
//         opened: true,
//       },
//       badges: {
//         textExtendedBadges: [
//           {
//             iconId: "guiltfree/GF_Logo_android_3x",
//             shortDescription: "options available",
//             fontColor: "#7E808C",
//           },
//         ],
//       },
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {
//             badgeObject: [
//               {
//                 attributes: {
//                   description: "",
//                   fontColor: "#7E808C",
//                   iconId: "guiltfree/GF_Logo_android_3x",
//                   shortDescription: "options available",
//                 },
//               },
//             ],
//           },
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/box8-desi-meals-harlur-main-road-hsr-layout-bangalore-289257",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "50467",
//       name: "Bakingo",
//       cloudinaryImageId: "0c53fd8f62e3d25ba56d1b4cfe572cef",
//       locality: "1st Block",
//       areaName: "Koramangala",
//       costForTwo: "₹300 for two",
//       cuisines: ["Bakery", "Desserts", "Beverages", "Snacks"],
//       avgRating: 4.3,
//       parentId: "3818",
//       avgRatingString: "4.3",
//       totalRatingsString: "5K+",
//       sla: {
//         deliveryTime: 33,
//         lastMileTravel: 6.5,
//         serviceability: "SERVICEABLE",
//         slaString: "33 mins",
//         lastMileTravelString: "6.5 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-07 01:00:00",
//         opened: true,
//       },
//       badges: {},
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {},
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/bakingo-1st-block-koramangala-bangalore-50467",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "27996",
//       name: "WarmOven Cake & Desserts",
//       cloudinaryImageId: "e938fb5f416cc2c28b4b519cf27b04cc",
//       locality: "2nd Sector",
//       areaName: "HSR Layout",
//       costForTwo: "₹200 for two",
//       cuisines: ["Bakery", "Desserts", "Ice Cream", "Beverages"],
//       avgRating: 4.2,
//       parentId: "9696",
//       avgRatingString: "4.2",
//       totalRatingsString: "5K+",
//       sla: {
//         deliveryTime: 37,
//         lastMileTravel: 3.8,
//         serviceability: "SERVICEABLE",
//         slaString: "37 mins",
//         lastMileTravelString: "3.8 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-07 05:00:00",
//         opened: true,
//       },
//       badges: {},
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {},
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/warmoven-cake-and-desserts-2nd-sector-hsr-layout-bangalore-27996",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "132112",
//       name: "Sharief Bhai",
//       cloudinaryImageId: "9ca4ac15ca5cdee1e71efe15909d465f",
//       locality: "Electronic City",
//       areaName: "Electronic City",
//       costForTwo: "₹400 for two",
//       cuisines: [
//         "Biryani",
//         "Mughlai",
//         "Arabian",
//         "Kebabs",
//         "Desserts",
//         "Beverages",
//       ],
//       avgRating: 4.1,
//       parentId: "5734",
//       avgRatingString: "4.1",
//       totalRatingsString: "10K+",
//       sla: {
//         deliveryTime: 34,
//         lastMileTravel: 6,
//         serviceability: "SERVICEABLE",
//         slaString: "34 mins",
//         lastMileTravelString: "6.0 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-06 23:59:00",
//         opened: true,
//       },
//       badges: {},
//       select: true,
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {},
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/sharief-bhai-electronic-city-bangalore-132112",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "374909",
//       name: "Thalassery Restaurant",
//       cloudinaryImageId: "fc4kehquqhqbvctqscaq",
//       locality: "Harlur Main Road",
//       areaName: "HSR Layout",
//       costForTwo: "₹400 for two",
//       cuisines: ["Indian", "Chinese", "Desserts", "Beverages"],
//       avgRating: 4.2,
//       parentId: "413366",
//       avgRatingString: "4.2",
//       totalRatingsString: "1K+",
//       sla: {
//         deliveryTime: 25,
//         lastMileTravel: 1.5,
//         serviceability: "SERVICEABLE",
//         slaString: "25 mins",
//         lastMileTravelString: "1.5 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-06 23:00:00",
//         opened: true,
//       },
//       badges: {},
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {},
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/thalassery-restaurant-harlur-main-road-hsr-layout-bangalore-374909",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "386368",
//       name: "KFC",
//       cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
//       locality: "Kasavanhalli",
//       areaName: "Bellandur",
//       costForTwo: "₹400 for two",
//       cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
//       avgRating: 4.2,
//       parentId: "547",
//       avgRatingString: "4.2",
//       totalRatingsString: "5K+",
//       sla: {
//         deliveryTime: 22,
//         lastMileTravel: 3.5,
//         serviceability: "SERVICEABLE",
//         slaString: "22 mins",
//         lastMileTravelString: "3.5 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-06 23:00:00",
//         opened: true,
//       },
//       badges: {},
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {},
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/kfc-kasavanhalli-bellandur-bangalore-386368",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "240736",
//       name: "Pizza Hut",
//       cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
//       locality: "Garvebhavipalya",
//       areaName: "Kudlu Gate",
//       costForTwo: "₹350 for two",
//       cuisines: ["Pizzas"],
//       avgRating: 4,
//       parentId: "721",
//       avgRatingString: "4.0",
//       totalRatingsString: "5K+",
//       sla: {
//         deliveryTime: 37,
//         lastMileTravel: 3,
//         serviceability: "SERVICEABLE",
//         slaString: "37 mins",
//         lastMileTravelString: "3.0 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-07 02:00:00",
//         opened: true,
//       },
//       badges: {},
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {},
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/pizza-hut-garvebhavipalya-kudlu-gate-bangalore-240736",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "23682",
//       name: "McDonald's",
//       cloudinaryImageId: "bb7ae131544c7d37e10fc5faf76f09d6",
//       locality: "HSR Layout",
//       areaName: "HSR Layout",
//       costForTwo: "₹400 for two",
//       cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
//       avgRating: 4.3,
//       parentId: "630",
//       avgRatingString: "4.3",
//       totalRatingsString: "10K+",
//       sla: {
//         deliveryTime: 32,
//         lastMileTravel: 5,
//         serviceability: "SERVICEABLE",
//         slaString: "32 mins",
//         lastMileTravelString: "5.0 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-07 02:45:00",
//         opened: true,
//       },
//       badges: {
//         textExtendedBadges: [
//           {
//             iconId: "guiltfree/GF_Logo_android_3x",
//             shortDescription: "options available",
//             fontColor: "#7E808C",
//           },
//         ],
//       },
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {
//             badgeObject: [
//               {
//                 attributes: {
//                   description: "",
//                   fontColor: "#7E808C",
//                   iconId: "guiltfree/GF_Logo_android_3x",
//                   shortDescription: "options available",
//                 },
//               },
//             ],
//           },
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/mcdonalds-hsr-layout-bangalore-23682",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "214485",
//       name: "CakeZone",
//       cloudinaryImageId: "e386a679bad57c2527925e5a22cd283a",
//       locality: "MADIWALA POST",
//       areaName: "ROOPENA AGRAHARA",
//       costForTwo: "₹200 for two",
//       cuisines: ["Bakery", "Desserts", "Sweets", "Ice Cream"],
//       avgRating: 4.3,
//       parentId: "7003",
//       avgRatingString: "4.3",
//       totalRatingsString: "5K+",
//       sla: {
//         deliveryTime: 34,
//         lastMileTravel: 5.5,
//         serviceability: "SERVICEABLE",
//         slaString: "34 mins",
//         lastMileTravelString: "5.5 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-07 02:00:00",
//         opened: true,
//       },
//       badges: {
//         textExtendedBadges: [
//           {
//             iconId: "guiltfree/GF_Logo_android_3x",
//             shortDescription: "options available",
//             fontColor: "#7E808C",
//           },
//         ],
//       },
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {
//             badgeObject: [
//               {
//                 attributes: {
//                   description: "",
//                   fontColor: "#7E808C",
//                   iconId: "guiltfree/GF_Logo_android_3x",
//                   shortDescription: "options available",
//                 },
//               },
//             ],
//           },
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/cakezone-madiwala-post-roopena-agrahara-bangalore-214485",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "8069",
//       name: "Theobroma",
//       cloudinaryImageId: "b033728dcb0101ceb19bff0e1e1f6474",
//       locality: "Daddakanahalli",
//       areaName: "Sarjapur Road",
//       costForTwo: "₹400 for two",
//       cuisines: ["Bakery"],
//       avgRating: 4.5,
//       parentId: "1040",
//       avgRatingString: "4.5",
//       totalRatingsString: "1K+",
//       sla: {
//         deliveryTime: 29,
//         lastMileTravel: 6.1,
//         serviceability: "SERVICEABLE",
//         slaString: "29 mins",
//         lastMileTravelString: "6.1 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-06 23:00:00",
//         opened: true,
//       },
//       badges: {
//         imageBadges: [
//           {
//             imageId: "newg.png",
//             description: "Gourmet",
//           },
//         ],
//       },
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {
//             badgeObject: [
//               {
//                 attributes: {
//                   description: "Gourmet",
//                   imageId: "newg.png",
//                 },
//               },
//             ],
//           },
//           textBased: {},
//           textExtendedBadges: {},
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/theobroma-daddakanahalli-sarjapur-road-bangalore-8069",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "43850",
//       name: "The Nosh House",
//       cloudinaryImageId: "t6c2esjgibs3nluwubvk",
//       locality: "Kasavanahalli",
//       areaName: "Sarjapur Road",
//       costForTwo: "₹600 for two",
//       cuisines: [
//         "Desserts",
//         "Bakery",
//         "Continental",
//         "Italian",
//         "American",
//         "Mediterranean",
//         "Mexican",
//         "Thai",
//         "Asian",
//         "Pan-Asian",
//         "Home Food",
//         "Healthy Food",
//         "Snacks",
//         "Pizzas",
//         "Pastas",
//         "Salads",
//         "Beverages",
//       ],
//       avgRating: 4.5,
//       parentId: "21005",
//       avgRatingString: "4.5",
//       totalRatingsString: "10K+",
//       sla: {
//         deliveryTime: 36,
//         lastMileTravel: 5,
//         serviceability: "SERVICEABLE",
//         slaString: "36 mins",
//         lastMileTravelString: "5.0 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-06 22:30:00",
//         opened: true,
//       },
//       badges: {
//         textExtendedBadges: [
//           {
//             iconId: "guiltfree/GF_Logo_android_3x",
//             shortDescription: "options available",
//             fontColor: "#7E808C",
//           },
//         ],
//       },
//       isOpen: true,
//       type: "C",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {
//             badgeObject: [
//               {
//                 attributes: {
//                   description: "",
//                   fontColor: "#7E808C",
//                   iconId: "guiltfree/GF_Logo_android_3x",
//                   shortDescription: "options available",
//                 },
//               },
//             ],
//           },
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/the-nosh-house-kasavanahalli-sarjapur-road-bangalore-43850",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "210192",
//       name: "Sweet Truth - Cake and Desserts",
//       cloudinaryImageId: "81cf6bfe2760a45a0caf2e28716ca4d7",
//       locality: "AECS Layout",
//       areaName: "Singasandra",
//       costForTwo: "₹450 for two",
//       cuisines: ["Snacks", "Bakery", "Desserts", "Beverages"],
//       avgRating: 4.5,
//       parentId: "4444",
//       avgRatingString: "4.5",
//       totalRatingsString: "100+",
//       sla: {
//         deliveryTime: 26,
//         lastMileTravel: 1.9,
//         serviceability: "SERVICEABLE",
//         slaString: "26 mins",
//         lastMileTravelString: "1.9 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-06 23:59:00",
//         opened: true,
//       },
//       badges: {},
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {},
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/sweet-truth-cake-and-desserts-aecs-layout-singasandra-bangalore-210192",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "376310",
//       name: "Baskin Robbins - Ice Cream Desserts",
//       cloudinaryImageId: "85ccae4e3576f9330af102c46ca85395",
//       locality: "A Block",
//       areaName: "Aecs Layout",
//       costForTwo: "₹250 for two",
//       cuisines: ["Desserts", "Ice Cream"],
//       avgRating: 4.4,
//       veg: true,
//       parentId: "5588",
//       avgRatingString: "4.4",
//       totalRatingsString: "100+",
//       sla: {
//         deliveryTime: 22,
//         lastMileTravel: 1.9,
//         serviceability: "SERVICEABLE",
//         slaString: "22 mins",
//         lastMileTravelString: "1.9 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-06 23:59:00",
//         opened: true,
//       },
//       badges: {},
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {},
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/baskin-robbins-ice-cream-desserts-a-block-aecs-layout-bangalore-376310",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "293027",
//       name: "Istah - The Mediterranean Way",
//       cloudinaryImageId: "9a01f2935fcb5ae05426db8264062102",
//       locality: "Vinayaka Nagar",
//       areaName: "Kudlu Gate",
//       costForTwo: "₹250 for two",
//       cuisines: [
//         "Mediterranean",
//         "Snacks",
//         "Biryani",
//         "Grill",
//         "Kebabs",
//         "Arabian",
//         "Lebanese",
//         "Beverages",
//         "Desserts",
//         "Italian",
//         "Turkish",
//       ],
//       avgRating: 4.4,
//       parentId: "3518",
//       avgRatingString: "4.4",
//       totalRatingsString: "5K+",
//       sla: {
//         deliveryTime: 27,
//         lastMileTravel: 1.4,
//         serviceability: "SERVICEABLE",
//         slaString: "27 mins",
//         lastMileTravelString: "1.4 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-06 23:30:00",
//         opened: true,
//       },
//       badges: {
//         imageBadges: [
//           {
//             imageId: "v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png",
//             description: "OnlyOnSwiggy",
//           },
//         ],
//       },
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {
//             badgeObject: [
//               {
//                 attributes: {
//                   description: "OnlyOnSwiggy",
//                   imageId:
//                     "v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png",
//                 },
//               },
//             ],
//           },
//           textBased: {},
//           textExtendedBadges: {},
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "EVERY ITEM",
//         subHeader: "@ ₹139",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/istah-the-mediterranean-way-vinayaka-nagar-kudlu-gate-bangalore-293027",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "320252",
//       name: "Social",
//       cloudinaryImageId: "zcjvolihd1vhx9g8ymsj",
//       locality: "Begur Hobli",
//       areaName: "Bommanahalli",
//       costForTwo: "₹600 for two",
//       cuisines: [
//         "Chinese",
//         "Fast Food",
//         "Biryani",
//         "Pizzas",
//         "Salads",
//         "Kebabs",
//         "Juices",
//         "Desserts",
//         "Beverages",
//       ],
//       avgRating: 4.2,
//       parentId: "2146",
//       avgRatingString: "4.2",
//       totalRatingsString: "1K+",
//       sla: {
//         deliveryTime: 36,
//         lastMileTravel: 4.8,
//         serviceability: "SERVICEABLE",
//         slaString: "36 mins",
//         lastMileTravelString: "4.8 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-07 02:30:00",
//         opened: true,
//       },
//       badges: {},
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {},
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/social-begur-hobli-bommanahalli-bangalore-320252",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "4750",
//       name: "Subway",
//       cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b",
//       locality: "Kaikondrahalli",
//       areaName: "Sarjapur Road",
//       costForTwo: "₹350 for two",
//       cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
//       avgRating: 4.2,
//       parentId: "2",
//       avgRatingString: "4.2",
//       totalRatingsString: "10K+",
//       sla: {
//         deliveryTime: 32,
//         lastMileTravel: 4.6,
//         serviceability: "SERVICEABLE",
//         slaString: "32 mins",
//         lastMileTravelString: "4.6 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-07 03:00:00",
//         opened: true,
//       },
//       badges: {
//         textExtendedBadges: [
//           {
//             iconId: "guiltfree/GF_Logo_android_3x",
//             shortDescription: "options available",
//             fontColor: "#7E808C",
//           },
//         ],
//       },
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {
//             badgeObject: [
//               {
//                 attributes: {
//                   description: "",
//                   fontColor: "#7E808C",
//                   iconId: "guiltfree/GF_Logo_android_3x",
//                   shortDescription: "options available",
//                 },
//               },
//             ],
//           },
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/subway-kaikondrahalli-sarjapur-road-bangalore-4750",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "248725",
//       name: "Natural Ice Cream",
//       cloudinaryImageId: "i9k1vtlizc0cnx6io8rv",
//       locality: "7th Sector",
//       areaName: "HSR Layout",
//       costForTwo: "₹150 for two",
//       cuisines: ["Ice Cream", "Desserts"],
//       avgRating: 4.7,
//       veg: true,
//       parentId: "2093",
//       avgRatingString: "4.7",
//       totalRatingsString: "5K+",
//       sla: {
//         deliveryTime: 32,
//         lastMileTravel: 4.9,
//         serviceability: "SERVICEABLE",
//         slaString: "32 mins",
//         lastMileTravelString: "4.9 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-07 01:00:00",
//         opened: true,
//       },
//       badges: {},
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {},
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "₹120 OFF",
//         subHeader: "ABOVE ₹199",
//         discountTag: "FLAT DEAL",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/natural-ice-cream-7th-sector-hsr-layout-bangalore-248725",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "146387",
//       name: "The Bowl Company",
//       cloudinaryImageId: "bb6049fae59b8a2413a9177eb0338b49",
//       locality: "Vinayaka Nagar",
//       areaName: "Kudlu Gate",
//       costForTwo: "₹300 for two",
//       cuisines: [
//         "Pan-Asian",
//         "Continental",
//         "North Indian",
//         "Desserts",
//         "American",
//         "Asian",
//         "Beverages",
//         "Biryani",
//         "Chinese",
//         "European",
//         "Grill",
//         "Hyderabadi",
//         "Indian",
//         "Italian",
//         "Kebabs",
//         "Lucknowi",
//         "Mediterranean",
//         "Mexican",
//         "Mughlai",
//         "Oriental",
//         "Pastas",
//         "Punjabi",
//         "Raja",
//       ],
//       avgRating: 4.4,
//       parentId: "4317",
//       avgRatingString: "4.4",
//       totalRatingsString: "10K+",
//       sla: {
//         deliveryTime: 26,
//         lastMileTravel: 1.4,
//         serviceability: "SERVICEABLE",
//         slaString: "26 mins",
//         lastMileTravelString: "1.4 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-06 23:30:00",
//         opened: true,
//       },
//       badges: {
//         imageBadges: [
//           {
//             imageId: "v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png",
//             description: "OnlyOnSwiggy",
//           },
//         ],
//       },
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {
//             badgeObject: [
//               {
//                 attributes: {
//                   description: "OnlyOnSwiggy",
//                   imageId:
//                     "v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png",
//                 },
//               },
//             ],
//           },
//           textBased: {},
//           textExtendedBadges: {},
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "EVERY ITEM",
//         subHeader: "@ ₹139",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/the-bowl-company-vinayaka-nagar-kudlu-gate-bangalore-146387",
//       type: "WEBLINK",
//     },
//   },
//   {
//     info: {
//       id: "69138",
//       name: "NIC Ice Creams",
//       cloudinaryImageId: "85825a6d74b1059a63a9b688de9f67ce",
//       locality: "4th Sector",
//       areaName: "HSR Layout",
//       costForTwo: "₹120 for two",
//       cuisines: ["Ice Cream", "Desserts"],
//       avgRating: 4.6,
//       veg: true,
//       parentId: "6249",
//       avgRatingString: "4.6",
//       totalRatingsString: "10K+",
//       sla: {
//         deliveryTime: 28,
//         lastMileTravel: 5,
//         serviceability: "SERVICEABLE",
//         slaString: "28 mins",
//         lastMileTravelString: "5.0 km",
//         iconType: "ICON_TYPE_EMPTY",
//       },
//       availability: {
//         nextCloseTime: "2024-01-06 23:00:00",
//         opened: true,
//       },
//       badges: {
//         textExtendedBadges: [
//           {
//             iconId: "guiltfree/GF_Logo_android_3x",
//             shortDescription: "brand",
//             fontColor: "#7E808C",
//           },
//         ],
//       },
//       isOpen: true,
//       type: "F",
//       badgesV2: {
//         entityBadges: {
//           imageBased: {},
//           textBased: {},
//           textExtendedBadges: {
//             badgeObject: [
//               {
//                 attributes: {
//                   description: "",
//                   fontColor: "#7E808C",
//                   iconId: "guiltfree/GF_Logo_android_3x",
//                   shortDescription: "brand",
//                 },
//               },
//             ],
//           },
//         },
//       },
//       aggregatedDiscountInfoV3: {
//         header: "ITEMS",
//         subHeader: "AT ₹169",
//       },
//       differentiatedUi: {
//         displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
//         differentiatedUiMediaDetails: {
//           mediaType: "ADS_MEDIA_ENUM_IMAGE",
//           lottie: {},
//           video: {},
//         },
//       },
//       reviewsSummary: {},
//       displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
//       restaurantOfferPresentationInfo: {},
//     },
//     analytics: {},
//     cta: {
//       link: "https://www.swiggy.com/restaurants/nic-ice-creams-4th-sector-hsr-layout-bangalore-69138",
//       type: "WEBLINK",
//     },
//   },
// ];
